steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/note-be-daino", "."]
    dir: 'backend'

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/note-be-daino"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be",
        "--image",
        "gcr.io/$PROJECT_ID/note-be-daino",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
